/**
 * Deciding what a documentation pull request should contain — as a pure
 * function, because this is the one place where DocDrift proposes changes to
 * someone's repository and every refusal here is a change that does not happen.
 *
 * The checks are deliberately strict. A suggestion is only included if a human
 * approved it; an analysis of a commit that is no longer the pull request's head
 * is refused rather than applied to newer code; and two approved suggestions for
 * the same document are refused rather than silently letting one overwrite the
 * other, because each holds a complete file.
 *
 * APPLIED counts as approved here. Every attempt builds its commit on the pull
 * request's head rather than on the previous documentation commit, so the plan
 * must always describe the WHOLE branch: if a second attempt carried only the
 * newly approved document, the ones applied first would disappear from it.
 */

export interface PlanInput {
  run: { id: string; status: string; headSha: string };
  pullRequest: { number: number; headSha: string; headRef: string; title: string };
  /** Approved suggestions only — the caller filters, this verifies. */
  suggestions: { id: string; documentationPath: string; currentContent: string; status: string }[];
  actorLogin: string;
}

export interface DocsPullRequestPlan {
  branch: string;
  base: string;
  title: string;
  commitMessage: string;
  body: string;
  files: { path: string; content: string }[];
  suggestionIds: string[];
}

export type PlanResult =
  | { ok: true; plan: DocsPullRequestPlan }
  | { ok: false; code: string; message: string };

/**
 * A branch of our own, named after the pull request and the analysis run, so a
 * second attempt at the same run reuses it (idempotent) while a later run gets
 * its own. The `docdrift/` prefix keeps it clearly ours: nothing else is ever
 * force-updated.
 */
export function branchName(prNumber: number, runId: string) {
  return `docdrift/pr-${prNumber}-${runId.slice(-8)}`;
}

export function planDocsPullRequest(input: PlanInput): PlanResult {
  const { run, pullRequest: pr, suggestions } = input;

  if (run.status !== 'SUCCEEDED')
    return {
      ok: false,
      code: 'ANALYSIS_NOT_SUCCEEDED',
      message: `This analysis is ${run.status.toLowerCase()}, so there is nothing to apply`,
    };

  // APPLIED means "approved earlier and already on the branch" — see above.
  const approved = suggestions.filter((s) => s.status === 'APPROVED' || s.status === 'APPLIED');
  if (approved.length === 0)
    return {
      ok: false,
      code: 'NOTHING_APPROVED',
      message: 'Approve at least one suggestion before opening a documentation pull request',
    };

  // The analysis read one commit. If the branch has moved, its suggestions may
  // describe code that no longer exists; re-run rather than apply blindly.
  if (run.headSha !== pr.headSha)
    return {
      ok: false,
      code: 'STALE_ANALYSIS',
      message: `This analysis read commit ${run.headSha.slice(0, 7)} but the pull request is now at ${pr.headSha.slice(0, 7)}. Run the analysis again.`,
    };

  const paths = approved.map((s) => s.documentationPath);
  const duplicate = paths.find((p, i) => paths.indexOf(p) !== i);
  if (duplicate)
    return {
      ok: false,
      code: 'CONFLICTING_SUGGESTIONS',
      message: `Two approved suggestions both rewrite ${duplicate}. Reject one of them: each contains a complete file, so applying both would lose one.`,
    };

  const list = approved.map((s) => `- \`${s.documentationPath}\``).join('\n');
  return {
    ok: true,
    plan: {
      branch: branchName(pr.number, run.id),
      // Into the pull request's own branch, so merging this puts the
      // documentation alongside the code change that made it necessary —
      // rather than landing separately on the default branch.
      base: pr.headRef,
      title: `docs: update documentation for #${pr.number}`,
      commitMessage: [
        `docs: update documentation for #${pr.number}`,
        '',
        `${approved.length} document(s) updated:`,
        list,
      ].join('\n'),
      body: [
        `Documentation that **#${pr.number} — ${pr.title}** appears to have made out of date.`,
        '',
        `${approved.length} change(s), each reviewed and approved by @${input.actorLogin}:`,
        '',
        list,
        '',
        '---',
        `Generated by DocDrift from analysis \`${run.id}\` of commit \`${run.headSha.slice(0, 7)}\`.`,
        'Every change here was approved by a person before this pull request was opened.',
        'Merging it into this branch keeps the documentation with the code change.',
      ].join('\n'),
      files: approved.map((s) => ({ path: s.documentationPath, content: s.currentContent })),
      suggestionIds: approved.map((s) => s.id),
    },
  };
}
